### ISSUE TITLE
Fix babble multipleresults

### ISSUE THREAD

**Issue by pefoley2** [tjcsl/cslbot#1330]
ERROR:backtrace:Traceback (most recent call last):
ERROR:backtrace:  File "/usr/local/virtualenvs/cslbot/lib/python3.5/site-packages/cslbot/helpers/command.py", line 69, in wrapper
ERROR:backtrace:    func(send, msg, args)
ERROR:backtrace:  File "/usr/local/virtualenvs/cslbot/lib/python3.5/site-packages/cslbot/commands/babble.py", line 96, in cmd
ERROR:backtrace:    send(build_msg(args['db'], cmdargs.speaker, cmdargs.length, cmdargs.start))
ERROR:backtrace:  File "/usr/local/virtualenvs/cslbot/lib/python3.5/site-packages/cslbot/commands/babble.py", line 45, in build_msg
ERROR:backtrace:    Babble_count.key == speaker).scalar()
ERROR:backtrace:  File "/usr/local/virtualenvs/cslbot/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2749, in scalar
ERROR:backtrace:    ret = self.one()
ERROR:backtrace:  File "/usr/local/virtualenvs/cslbot/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2727, in one
ERROR:backtrace:    "Multiple rows were found for one()")
ERROR:backtrace:sqlalchemy.orm.exc.MultipleResultsFound: Multiple rows were found for one()

**Comment by pefoley2** [comment]
Reproducible with !babble jcena

**Comment by pefoley2** [comment]
Should be fixed by 320e854b8047d6fdb960b
